spring.application.name=SpringCoreDemo4.2

# payment-gateway.type=paytm
# payment-gateway.retrycnt=4

payment-property.type=paytm
payment-property.retrycnt=5
payment-property.enabled=true
payment-property.timeout=3000